function createfigure(Record1)
%CREATEFIGURE(Record1)
%  RECORD1:  vector of y data

%  Auto-generated by MATLAB on 25-Sep-2024 18:02:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create semilogy
semilogy1 = semilogy(Record1,'ZDataSource','',...
    'DisplayName','Noiseless case',...
    'LineWidth',2.8,...
    'Color',[0 0 0]);

% The following line demonstrates an alternative way to create a data tip.
% datatip(semilogy1,3439995,5.21682516693529e-13);
% Create datatip
% datatip(semilogy1,'DataIndex',size(Record1,1),'Location','northeast');

% Create ylabel
ylabel({'Loss'});

% Create xlabel
xlabel({'k'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-2493.11224920981 3497506.88775079]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1.26753541668304e-14 1267535.41668303]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','times','FontSize',35,'LineWidth',1.5,'YMinorTick',...
    'on','YScale','log');
% Create legend
legend(axes1,'show');
set (gca,'position',[0.15,0.15,0.8,0.8] );%axis位置，最下角，宽高
set(gcf,'unit','inches','position',[0,0,10,10]);%figture位置，最下角，宽高
hold on

